# ─── sandbox help ─────────────────────────────────────────────────────────────
# Sourced by sandbox.sh — handles: sandbox <action> -h | --help
# Variables inherited: ACTION, logging/color functions
# ─────────────────────────────────────────────────────────────────────────────

case "$ACTION" in
    conn)
        echo ""
        echo -e "  ${CYAN}sandbox conn${NC} — MCP connection manager"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox conn <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}list${NC}     List all saved connections"
        echo -e "    ${CYAN}add${NC}      Add a new saved connection"
        echo -e "    ${CYAN}delete${NC}   Delete a saved connection"
        echo -e "    ${CYAN}test${NC}     Test a saved connection"
        echo ""
        echo -e "  ${YELLOW}Parameters (add):${NC}"
        echo -e "    ${CYAN}--name${NC}  <name>       Required. Connection name"
        echo -e "    ${CYAN}--user${NC}  <user>       Required. Database user"
        echo -e "    ${CYAN}--pass${NC}  <password>   Optional. Default: env password"
        echo -e "    ${CYAN}--host${NC}  <host>       Optional. Default: env host"
        echo -e "    ${CYAN}--port${NC}  <port>       Optional. Default: env port"
        echo -e "    ${CYAN}--pdb${NC}   <PDB name>   Optional. Default: env service"
        echo ""
        echo -e "  ${YELLOW}Parameters (delete / test):${NC}"
        echo -e "    ${CYAN}--name${NC}  <name>   Required. Connection name"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox conn list"
        echo -e "    sandbox conn add --name sandbox-mcp --user demasy_ai --pdb DEMASYLABS_PDB"
        echo -e "    sandbox conn test --name sandbox-mcp"
        echo -e "    sandbox conn delete --name sandbox-mcp"
        echo ""
        ;;
    logs)
        echo ""
        echo -e "  ${CYAN}sandbox logs${NC} — View sandbox log files"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox logs <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}      APEX installation logs"
        echo -e "    ${CYAN}install${NC}   All installation logs (APEX + ORDS)"
        echo -e "    ${CYAN}ords${NC}      ORDS runtime log"
        echo -e "    ${CYAN}startup${NC}   Container startup / user-setup log"
        echo -e "    ${CYAN}mcp${NC}       MCP server log"
        echo -e "    ${CYAN}all${NC}       All log files combined"
        echo ""
        echo -e "  ${YELLOW}Parameters:${NC}"
        echo -e "    ${CYAN}-f${NC}, ${CYAN}--follow${NC}        Stream log output (like tail -f)"
        echo -e "    ${CYAN}-n${NC}, ${CYAN}--lines${NC} <N>     Number of lines to show (default: 50)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox logs startup"
        echo -e "    sandbox logs apex"
        echo -e "    sandbox logs ords --follow"
        echo -e "    sandbox logs install --lines 100"
        echo -e "    sandbox logs all"
        echo ""
        ;;
    status)
        echo ""
        echo -e "  ${CYAN}sandbox status${NC} — Show running status of a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox status <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}database${NC}  Oracle database — port and SQL connectivity"
        echo -e "    ${CYAN}apex${NC}      APEX/ORDS — process, port, HTTP endpoints"
        echo -e "    ${CYAN}mcp${NC}       MCP server — process check"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox status database"
        echo -e "    sandbox status apex"
        echo -e "    sandbox status mcp"
        echo ""
        ;;
    run)
        echo ""
        echo -e "  ${CYAN}sandbox run${NC} — Connect to or run a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox run <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}sqlcl${NC}        Open an interactive SQLcl session"
        echo -e "    ${CYAN}mcp${NC}          Run the MCP server"
        echo -e "    ${CYAN}healthcheck${NC}  Run the Oracle sandbox healthcheck"
        echo ""
        echo -e "  ${YELLOW}Parameters (sqlcl):${NC}"
        echo -e "    ${CYAN}-u${NC}, ${CYAN}--user${NC} <user>       Required. Database user to connect as"
        echo -e "    ${CYAN}-p${NC}, ${CYAN}--pass${NC} <password>   Optional. Default: Default Password"
        echo ""
        echo -e "  ${YELLOW}Valid users:${NC}"
        echo -e "    ${CYAN}sys${NC}          SYS (sysdba) — CDB root"
        echo -e "    ${CYAN}system${NC}       SYSTEM — CDB root"
        echo -e "    ${CYAN}sandbox${NC}      SANDBOX — application user (PDB)"
        echo -e "    ${CYAN}sandbox_ai${NC}   SANDBOX_AI — AI/MCP user (PDB)"
        echo -e "    ${CYAN}demasy${NC}       DEMASY — application user (PDB)"
        echo -e "    ${CYAN}demasy_ai${NC}    DEMASY_AI — AI/MCP user (PDB)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox run sqlcl --user system"
        echo -e "    sandbox run sqlcl --user demasy"
        echo -e "    sandbox run sqlcl -u sandbox"
        echo -e "    sandbox run sqlcl --user demasy --pass mypassword"
        echo -e "    sandbox run healthcheck"
        echo ""
        ;;
    start)
        echo ""
        echo -e "  ${CYAN}sandbox start${NC} — Start a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox start <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}         Start Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}          Start the MCP server"
        echo ""
        echo -e "  ${YELLOW}Parameters (mcp):${NC}"
        echo -e "    ${CYAN}-d${NC}, ${CYAN}--default${NC}                       Use the default saved connection"
        echo -e "    ${CYAN}-c${NC}, ${CYAN}--conn${NC} <name>  Use the specified saved connection"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox start apex"
        echo -e "    sandbox start mcp -d"
        echo -e "    sandbox start mcp -c sandbox-mcp-conn"
        echo -e "    sandbox start mcp --conn sandbox-mcp-conn"
        echo -e "    sandbox start mcp --conn demasy-mcp-conn"
        echo ""
        ;;
    stop)
        echo ""
        echo -e "  ${CYAN}sandbox stop${NC} — Stop a running service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox stop <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}     Stop Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}      Stop the MCP server"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox stop apex"
        echo ""
        ;;
    restart)
        echo ""
        echo -e "  ${CYAN}sandbox restart${NC} — Restart a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox restart <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}     Restart Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}      Restart the MCP server"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox restart apex"
        echo ""
        ;;
    install)
        echo ""
        echo -e "  ${CYAN}sandbox install${NC} — Install Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox install <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}      Install Oracle APEX + ORDS"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox install apex"
        echo ""
        ;;
    uninstall)
        echo ""
        echo -e "  ${CYAN}sandbox uninstall${NC} — Uninstall Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox uninstall <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}      Uninstall Oracle APEX + ORDS"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox uninstall apex"
        echo ""
        ;;
    download)
        echo ""
        echo -e "  ${CYAN}sandbox download${NC} — Download Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox download <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}   Download Oracle APEX"
        echo -e "    ${CYAN}ords${NC}   Download Oracle REST Data Services"
        echo ""
        echo -e "  ${YELLOW}Parameters (apex):${NC}"
        echo -e "    ${CYAN}-s${NC}, ${CYAN}--standalone${NC}   Download APEX only (without ORDS)"
        echo -e "    ${CYAN}-a${NC}, ${CYAN}--all${NC}          Download APEX + ORDS together"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox download apex -s"
        echo -e "    sandbox download apex --standalone"
        echo -e "    sandbox download apex -a"
        echo -e "    sandbox download apex --all"
        echo -e "    sandbox download ords"
        echo ""
        ;;
esac
