# ─── sandbox help ─────────────────────────────────────────────────────────────
# Sourced by sandbox.sh — handles: sandbox <action> -h | --help
# Variables inherited: ACTION, logging/color functions
# ─────────────────────────────────────────────────────────────────────────────

case "$ACTION" in
    download)
        echo ""
        echo -e "  ${CYAN}sandbox download${NC} — Download Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox download <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}   Download Oracle APEX"
        echo -e "    ${CYAN}ords${NC}   Download Oracle REST Data Services"
        echo ""
        echo -e "  ${YELLOW}Parameters (apex):${NC}"
        echo -e "    ${CYAN}-s${NC}, ${CYAN}-standalone${NC}   Download APEX only (without ORDS)"
        echo -e "    ${CYAN}-a${NC}, ${CYAN}--all${NC}         Download APEX + ORDS together"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox download apex -s"
        echo -e "    sandbox download apex -standalone"
        echo -e "    sandbox download apex -a"
        echo -e "    sandbox download apex --all"
        echo -e "    sandbox download ords"
        echo ""
        ;;
    install)
        echo ""
        echo -e "  ${CYAN}sandbox install${NC} — Install Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox install <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}oracle${NC}    Install Oracle Instant Client"
        echo -e "    ${CYAN}client${NC}    Install Oracle Instant Client (alias for oracle)"
        echo -e "    ${CYAN}sqlcl${NC}     Install Oracle SQLcl"
        echo -e "    ${CYAN}sqlplus${NC}   Install SQL*Plus"
        echo -e "    ${CYAN}apex${NC}      Install Oracle APEX + ORDS"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox install oracle"
        echo -e "    sandbox install sqlcl"
        echo -e "    sandbox install sqlplus"
        echo -e "    sandbox install apex"
        echo ""
        ;;
    uninstall)
        echo ""
        echo -e "  ${CYAN}sandbox uninstall${NC} — Uninstall Oracle components"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox uninstall <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}oracle${NC}    Uninstall Oracle Instant Client"
        echo -e "    ${CYAN}client${NC}    Uninstall Oracle Instant Client (alias for oracle)"
        echo -e "    ${CYAN}sqlcl${NC}     Uninstall Oracle SQLcl"
        echo -e "    ${CYAN}sqlplus${NC}   Uninstall SQL*Plus"
        echo -e "    ${CYAN}apex${NC}      Uninstall Oracle APEX + ORDS"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox uninstall apex"
        echo ""
        ;;
    start)
        echo ""
        echo -e "  ${CYAN}sandbox start${NC} — Start a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox start <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}         Start Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}          Start the MCP server"
        echo -e "    ${CYAN}system${NC}       Start system services"
        echo ""
        echo -e "  ${YELLOW}Parameters (mcp):${NC}"
        echo -e "    ${CYAN}-d${NC}, ${CYAN}--default${NC}              Use the default saved connection"
        echo -e "    ${CYAN}-conn${NC}, ${CYAN}--connection${NC} <name>  Use the specified saved connection"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox start apex"
        echo -e "    sandbox start mcp -d"
        echo -e "    sandbox start mcp --default"
        echo -e "    sandbox start mcp -conn mcp-saved"
        echo -e "    sandbox start mcp --connection mcp-saved"
        echo ""
        ;;
    stop)
        echo ""
        echo -e "  ${CYAN}sandbox stop${NC} — Stop a running service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox stop <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}     Stop Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}      Stop the MCP server"
        echo -e "    ${CYAN}system${NC}   Stop system services"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox stop apex"
        echo ""
        ;;
    restart)
        echo ""
        echo -e "  ${CYAN}sandbox restart${NC} — Restart a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox restart <resource>"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}apex${NC}     Restart Oracle APEX (ORDS)"
        echo -e "    ${CYAN}mcp${NC}      Restart the MCP server"
        echo -e "    ${CYAN}system${NC}   Restart system services"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox restart apex"
        echo ""
        ;;
    run)
        echo ""
        echo -e "  ${CYAN}sandbox run${NC} — Connect to or run a service"
        echo ""
        echo -e "  ${WHITE}Usage:${NC}     sandbox run <resource> [parameters]"
        echo ""
        echo -e "  ${YELLOW}Resources:${NC}"
        echo -e "    ${CYAN}sqlcl${NC}        Open an interactive SQLcl session"
        echo -e "    ${CYAN}mcp${NC}          Run the MCP server"
        echo -e "    ${CYAN}oracle${NC}       Run Oracle tools"
        echo -e "    ${CYAN}system${NC}       Run system utilities"
        echo -e "    ${CYAN}healthcheck${NC}  Run the Oracle sandbox healthcheck"
        echo ""
        echo -e "  ${YELLOW}Parameters (sqlcl):${NC}"
        echo -e "    ${CYAN}-user${NC} <user>       Required. Database user to connect as"
        echo -e "    ${CYAN}-pass${NC} <password>   Optional. Default: \$DEMASYLABS_DB_PASSWORD"
        echo ""
        echo -e "  ${YELLOW}Valid users:${NC}"
        echo -e "    ${CYAN}sys${NC}          SYS (sysdba) — CDB root"
        echo -e "    ${CYAN}system${NC}       SYSTEM — CDB root"
        echo -e "    ${CYAN}demasy${NC}       DEMASY — application user (PDB)"
        echo -e "    ${CYAN}sandbox${NC}      SANDBOX — application user (PDB)"
        echo -e "    ${CYAN}demasylabs${NC}   C##DEMASY — common user (PDB)"
        echo -e "    ${CYAN}demasy_ai${NC}    AI/MCP user (PDB)"
        echo ""
        echo -e "  ${YELLOW}Examples:${NC}"
        echo -e "    sandbox run sqlcl -user system"
        echo -e "    sandbox run sqlcl -user demasy"
        echo -e "    sandbox run sqlcl -user sandbox"
        echo -e "    sandbox run sqlcl -user sys"
        echo -e "    sandbox run sqlcl -user demasy_ai"
        echo -e "    sandbox run sqlcl -user demasy -pass mypassword"
        echo -e "    sandbox run healthcheck"
        echo ""
        ;;
esac
